### ISSUE TITLE
Unicode codepoints are used in the specification, but the specification does not define encoding

### ISSUE THREAD

**Issue by Agares** [php/php-langspec#233]
For example here:
https://github.com/php/php-langspec/blob/master/spec/19-grammar.md#grammar-name-nondigit
"one of the characters U+0080–U+00ff"

This statement is ambiguous if the encoding is not defined. What I believe would be correct is saying that PHP uses ASCII, but byes 0x80 to 0xFF might be allowed, as defined in the grammar, and then the grammar should read "one of the bytes 0x80 – 0xFF"

**Comment by nikic** [comment]
Right, bytes would be correct in this context.

**Comment by IMSoP** [comment]
You are right that the specification makes mistakes about encodings, but you have it the wrong way around: PHP source is handled as Unicode, not as ASCII.

You can prove this pretty easily, by [defining a function called 🐘](https://3v4l.org/TthsP). This clearly violates the [definition of a "name" in the current spec](https://github.com/php/php-langspec/blob/63375439ff7e8a1be93d0ef7d3c3b4833d5e35a0/spec/09-lexical-structure.md#names).

A quick search finds two direct references to encoding in the existing text. First, [Section 9: Lexical Structure](https://github.com/php/php-langspec/blob/63375439ff7e8a1be93d0ef7d3c3b4833d5e35a0/spec/09-lexical-structure.md) specifies:

> Step 1: Transformation, which converts a script from a particular character repertoire and encoding scheme into a sequence of 8-bit characters.

and

> Conforming implementations must accept scripts encoded with the UTF-8 encoding form (as defined by the Unicode standard), and transform them into a sequence of characters. Implementations can choose to accept and transform additional character encoding schemes.

Secondly, Section 11, under [the `declare` statement](https://github.com/php/php-langspec/blob/197a397cf84bdcd3f896aebf15a73b5fd45a174d/spec/11-statements.md#the-declare-statement), explains *how* such encodings are selected:

> encoding: character encoding can be specified on a script-by-script basis using the encoding directive. The joint ISO and IEC standard ISO/IEC 8859 standard series specifies a number of 8-bit-character encodings whose names can be used with this directive. This directive applies only to the file it appears in, and does not affect the included files.

Both reference "8-bit characters", a somewhat odd term, which doesn't really make any sense. I'm not sure why there's any mention of 8-bit at all here, since I'm pretty sure `declare(encoding=UTF-16);` is also supported.

**Comment by Agares** [comment]
```
<?php
$funcName = chr(0xff).chr(0xff).chr(0xff).chr(0xff);
file_put_contents('test2.php', '<?php function '.$funcName.'() { echo \'Hi\'; } ' . $funcName . '();');
```
This generates a PHP file which is not valid UTF-8. Yet the script works, and it would be correct if we assume "U+00##" means "byte 0x##" and the spec defined its encoding as "7-bit ASCII, where 0x80 to 0xFF are allowed"

**Comment by IMSoP** [comment]
OK, so the "encoding" of the parser is neither UTF-8 nor ASCII, since that string would be invalid in both. "7-bit ASCII, where 0x80 to 0xFF are allowed" is clearly a contradiction in terms, but "an ASCII-compatible encoding" as suggested by Nikita implies that *any* ASCII-compatible encoding is possible.

I think what is actually the case is that the parser treats the transformed source code as **a series of bytes**; bytes do not have an encoding, and a parser does not need to give them one. Within **the specification** (and, most likely, the source of an implementation), byte values are represented by their ASCII interpretations.

That makes your changes from U+0000 form to 0x00 form correct, because a conforming implementation could be written with no knowledge of ASCII by using those byte values.

**Comment by IMSoP** [comment]
Incidentally, I would love to go through and replace all instances of the word "character"; I think that word is almost always ambiguous, and should be avoided. In this case, I believe it should always say "byte".

**Comment by Agares** [comment]
The knowledge that characters 0x00 to 0x7F are encoded as ASCII is still required in the implementation, because otherwise e.g. if "}" is not encoded as 0x7D, then the script won't work, because the PHP interpreter expects that 0x7D means "}".
I agree that "ASCII, where 0x80 to 0xFF are allowed" might not be the perfect wording, maybe "but" instead of "where" would fix it?
I would like to avoid saying ASCII-compatible, as this raises the question of how it is compatbile? backwards? forwards?
And yes, I agree about replacing "character" with "byte.

**Comment by IMSoP** [comment]
In what sense does the implementation need to "know" that 0x7D "means" anything? The lexer simply reads a byte with value 0x7D and emits a particular token.

**Comment by Agares** [comment]
so the implementation has to map 0x7D to the token for "}", so if the specification defines that the character "}" (it does not specify the byte value) means something in some context, then the knowledge of how to map "}" to byte is the job of the person who implements the parser. So yes, the implementation doesn't need to "know" about what 0x7D means, but the person who reads the spec needs to know that "}" means 0x7D.

**Comment by IMSoP** [comment]
Yes, which is why I placed the emphasis on **the specification** using ASCII, rather than **the language** using ASCII. It would be possible to write the entire specification without any reliance on ASCII, by specifying every byte numerically; it's just more convenient for programmers to use a different notation.

**Comment by Agares** [comment]
The language uses ASCII. We can't pretend that `private` isn't `private`, but `0x70 0x72 0x69 0x76 0x61 0x74 0x65`.

**Comment by IMSoP** [comment]
Why not? A conforming parser need only care whether the string of bytes `0x70 0x72 0x69 0x76 0x61 0x74 0x65` appears in a particular location or not. By the same token, you could say that the language "uses English", but it would be perfectly possible to write a conforming implementation without the faintest clue what the word "private" means.

**Comment by Agares** [comment]
Yea, after giving this some more thought it makes sense :). I updated the PR with your proposed wording about encoding.

**Comment by IMSoP** [comment]
Apologies for my previous incorrect comments about Unicode. Nothing like character encodings to sow confusion and discord, eh? ;)

**Comment by Agares** [comment]
Hey, it's been a few weeks since we agreed on what to do. What do I need to do to get the PR merged?

**Comment by nikic** [comment]
Closing this as #234 has been merged.
